version: '3.9'

networks:
  defaultnetwork:

services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: OnlineApartmentReservationSystem.Db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "8002:1433"
    networks:
      - defaultnetwork
    volumes:
      - mssql-data:/var/opt/mssql

  onlineapartmentreservationsystem.api:
    image: ${DOCKER_REGISTRY-}onlineapartmentreservationsystemapi
    container_name: OnlineApartmentReservationSystem.Api
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: Presentation/OnlineApartmentReservationSystem.API/Dockerfile
    depends_on:
      - mssql-container
    networks:
      - defaultnetwork

volumes:
  mssql-data:
